[[tasks]]
url = "https://github.com/kpliuta/tt-sh-runner-example-task"

[[tasks]]
url = "https://github.com/kpliuta/tt-sh-runner-example-task"

[[tasks]]
url = "https://github.com/kpliuta/tt-sh-runner-example-task"
